# Generated by Django 2.2.6 on 2019-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=1)),
                ('localizacao_rua', models.CharField(max_length=30)),
                ('localizacao_cep', models.CharField(max_length=30)),
            ],
        ),
    ]
